### ISSUE TITLE
language switch 기능이 적용되지 않은 부분 수정

### ISSUE THREAD

**Issue by GanghyeonSeo** [gsainfoteam/meal-flutter#13]

**Comment by inthree3** [comment]
혹시 어떤 부분이 적용이 안 되고 있었을까요??

**Comment by inthree3** [comment]
아 풀리퀘스트할 때 필요한 건가용?

**Comment by GanghyeonSeo** [comment]
식단이 없을 때 출력되는 텍스트랑 setting page 부분 수정했습니다.

**Comment by inthree3** [comment]
아하 이미 수정된 사항이면 merge conflict하면 될 것 같고, 아니라면 식단 없을 때 출력되는 텍스트는 PR 코드에서 수정해두어서 패스하셔도 될 것 같아요!

**Comment by inthree3** [comment]
PR #11, PR #12 이슈 해결된 것으로 보여서 닫을게요! (혹시 아니면 다시 열어주세요... ㅎㅎ)
